version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - benchmark_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dujevidas
      POSTGRES_PASSWORD: DVidas123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - benchmark_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python-scripts:
    build: .
    depends_on:
      - redis
      - postgres
    networks:
      - benchmark_network
      
networks:
  benchmark_network:
    driver: bridge
